export const emotionStyles = {
    sadness: { emoji: "😢", bgColor: "bg-blue-200" },
    disappointment: { emoji: "😞", bgColor: "bg-purple-200" },
    grief: { emoji: "😭", bgColor: "bg-gray-200" },
    neutral: { emoji: "😐", bgColor: "bg-yellow-200" },
    remorse: { emoji: "😔", bgColor: "bg-green-200" },
    annoyance: { emoji: "😒", bgColor: "bg-orange-200" },
    realization: { emoji: "🤔", bgColor: "bg-teal-200" },
    caring: { emoji: "🥰", bgColor: "bg-pink-200" },
    approval: { emoji: "👍", bgColor: "bg-blue-300" },
    admiration: { emoji: "😍", bgColor: "bg-red-200" },
    disapproval: { emoji: "👎", bgColor: "bg-purple-300" },
    love: { emoji: "❤️", bgColor: "bg-pink-300" },
    joy: { emoji: "😄", bgColor: "bg-yellow-300" },
    anger: { emoji: "😠", bgColor: "bg-red-300" },
    amusement: { emoji: "😆", bgColor: "bg-orange-300" },
    nervousness: { emoji: "😬", bgColor: "bg-blue-400" },
    curiosity: { emoji: "🤨", bgColor: "bg-teal-300" },
    disgust: { emoji: "🤢", bgColor: "bg-green-300" },
    desire: { emoji: "😏", bgColor: "bg-purple-400" },
    gratitude: { emoji: "🙏", bgColor: "bg-yellow-400" },
    fear: { emoji: "😨", bgColor: "bg-gray-300" },
    confusion: { emoji: "😕", bgColor: "bg-orange-400" },
    optimism: { emoji: "😌", bgColor: "bg-green-400" },
    surprise: { emoji: "😲", bgColor: "bg-blue-500" },
    embarrassment: { emoji: "😳", bgColor: "bg-pink-400" },
    relief: { emoji: "😅", bgColor: "bg-blue-600" },
    excitement: { emoji: "🤩", bgColor: "bg-yellow-500" },
    pride: { emoji: "😤", bgColor: "bg-red-400" },
  };